services:
  trafic-legal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trafic-legal-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    networks:
      - euphoria_network

networks:
  euphoria_network:
    driver: bridge